default_model:
    type: openai
    name: gpt-4o-mini
    parameters:
      temperature: 0.7
      max_tokens: 8000


gemini_model:
  type: gemini
  name: gemini-2.0-flash-lite
  parameters:
    temperature: 0.5
    max_tokens: 4000

claude_model:
  type: claude
  name: claude-3-5-sonnet-20241022
  parameters:
    temperature: 0.5
    max_tokens: 4000

model_1:
  type: openai
  name: gpt-4o-mini
  parameters:
    temperature: 1.0
    max_tokens: 2048

model_2:
  type: openai
  name: gpt-4o-mini
  parameters:
    temperature: 0.5
    max_tokens: 2048

tools:
  - name: arxiv_search
    description: Search papers on arXiv
    parameters:
      max_results: 20          # default retrieve nums
      sort_by: "relevance"

  - name: semantic_scholar
    description: Fetch paper metadata from Semantic Scholar
    parameters:
      limit: 20
      fields: ["title", "abstract", "authors", "venue", "year"]

user_proxy:
  enable: true                # enable user reply（true/false）

workflow:
  survey:
    max_retries: 3            # retrieve max time
    min_papers: 8            # at least paper nums